services:
  - type: web
    name: planistry
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn PlanistryDemo.wsgi"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "planistry.onrender.com"
